import asyncio, json, datetime, os, sys
from playwright.async_api import async_playwright
ROOT=os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HERE=os.path.dirname(os.path.abspath(__file__))
URL="file://"+os.path.join(ROOT,"index.html")
SHOTS=os.path.join(HERE,"screenshots")
errors=[]
def check(cond,msg):
    print(("PASS " if cond else "FAIL ")+msg)
    if not cond: errors.append(msg)

async def main():
    async with async_playwright() as p:
        b=await p.chromium.launch()
        ctx=await b.new_context(viewport={"width":390,"height":844},device_scale_factor=2,is_mobile=True,has_touch=True,accept_downloads=True)
        page=await ctx.new_page()
        console=[]
        page.on("console", lambda m: console.append(f"{m.type}: {m.text}") if m.type in ("error","warning") else None)
        page.on("pageerror", lambda e: console.append(f"pageerror: {e}"))
        page.on("dialog", lambda d: asyncio.ensure_future(d.accept()))
        await page.goto(URL)
        check(await page.locator("text=Welcome to PawSteps").count()==1,"onboarding shown")
        # validation
        await page.click("[data-act=onb-save]")
        check(await page.locator("text=Welcome to PawSteps").count()==1,"onboarding blocks empty name")
        start=(datetime.date.today()-datetime.timedelta(days=3)).isoformat()
        await page.fill("#f-name","Biscuit")
        await page.click("[data-act=age][data-v=adolescent]")
        await page.fill("#f-breed","Golden Retriever mix")
        await page.fill("#f-start",start)
        await page.click("[data-act=onb-save]")
        h1=await page.locator(".day-hero h1").inner_text()
        check(h1=="Day 4 with Biscuit", f"hero says Day 4 with Biscuit (got {h1!r})")
        # Day 4 sessions
        await page.click("[data-act=sess][data-i='0']")
        await page.click("[data-act=sess][data-i='1']")
        check((await page.locator("#sess-count").inner_text())=="2/3 done","2/3 sessions checked")
        await page.click("[data-act=rate][data-v='3']")
        await page.fill("#notes","Biscuit loved the hand target! Got 8/10 touches from 1 ft away.")
        await page.wait_for_timeout(600)
        # previous days
        for d in (3,2,1):
            await page.click("[data-act=prev]")
            check((await page.locator(".day-hero h1").inner_text())==f"Day {d} with Biscuit", f"navigated back to Day {d}")
            n=await page.locator("[data-act=sess]").count()
            for i in range(n): await page.click(f"[data-act=sess][data-i='{i}']")
            await page.click(f"[data-act=rate][data-v='{3 if d!=3 else 2}']")
        await page.fill("#notes","Marker charged fast — head whips round on 'Yes!'.")
        await page.wait_for_timeout(500)
        await page.click("[data-act=master][data-id=marker]")
        await page.click("[data-act=today]")
        check((await page.locator(".day-hero h1").inner_text())=="Day 4 with Biscuit","back to today works")
        # timer
        t0=await page.locator("#tm-text").inner_text()
        await page.click("[data-act=tm-toggle]"); await page.wait_for_timeout(2300)
        t1=await page.locator("#tm-text").inner_text()
        await page.click("[data-act=tm-toggle]")
        st=await page.locator("#tm-state").inner_text()
        check(t0!=t1 and st=="paused", f"timer counts down and pauses ({t0}->{t1}, {st})")
        await page.click("[data-act=tm-add][data-s='60']")
        await page.click("[data-act=tm-reset]")
        check((await page.locator("#tm-text").inner_text())==t0,"timer reset")
        # reload persistence
        await page.reload()
        check((await page.locator("#sess-count").inner_text())=="2/3 done","sessions persist after reload")
        check("hand target" in (await page.locator("#notes").input_value()),"notes persist after reload")
        check(await page.locator("[data-act=rate][data-v='3'].on").count()==1,"rating persists after reload")
        # progress
        await page.click(".nav [data-r=progress]")
        stats=await page.locator(".stat .v").all_inner_texts()
        print("stats:",stats)
        check(stats[1]=="11" and stats[2].startswith("3") and stats[3]=="7%","progress stats correct (11 sessions, 3 days, 7%)")
        check(await page.locator(".cell.done").count()==3,"3 cells done in heatmap")
        check(await page.locator(".cell.partial").count()==1,"1 partial cell")
        check(await page.locator(".mbtn.on[data-id=marker]").count()==1,"marker mastered shown")
        # program
        await page.click(".nav [data-r=program]")
        check(await page.locator(".day-row").count()==42,"program lists 42 days")
        await page.click(".day-row[data-n='15']")
        check((await page.locator(".day-hero h1").inner_text())=="Day 15 with Biscuit","open day from program")
        check(await page.locator(".banner.warm").count()==1,"peek-ahead banner")
        # skills
        await page.click(".nav [data-r=skills]")
        await page.fill("#skill-search","door")
        vis=await page.locator(".skill-card:not([hidden])").count()
        check(0<vis<19, f"search filters skills ({vis} visible for 'door')")
        await page.fill("#skill-search","")
        await page.click("[data-act=filter][data-c=Tricks]")
        check(await page.locator(".skill-card:not([hidden])").count()==3,"Tricks filter shows 3")
        await page.click("[data-act=filter][data-c=Mastered]")
        check(await page.locator(".skill-card:not([hidden])").count()==1,"Mastered filter shows 1")
        await page.click("[data-act=filter][data-c=All]")
        await page.click(".skill-card[data-id=stay] summary")
        check(await page.locator(".skill-card[data-id=stay] .lib-day").count()==3,"Stay has 3 lesson days")
        # settings + export/import
        await page.click(".nav [data-r=settings]")
        async with page.expect_download() as dl:
            await page.click("[data-act=export]")
        d=await dl.value; path=os.path.join(HERE,"export.json"); await d.save_as(path)
        data=json.load(open(path)); check(data["state"]["profile"]["name"]=="Biscuit","export contains profile")
        # repeat day on today
        await page.click(".nav [data-r=today]")
        await page.click("[data-act=repeat]")
        await page.wait_for_timeout(300)
        check((await page.locator("#sess-count").inner_text())=="0/3 done","repeat clears sessions")
        check(await page.locator("text=Attempt #2").count()==1,"repeat shows attempt history")
        rep=await page.evaluate("JSON.parse(localStorage.getItem('pawsteps-dog-training-v1')).repeats")
        check(len(rep)==1,"repeat schedules shift for tomorrow")
        # reset
        await page.click(".nav [data-r=settings]")
        await page.click("[data-act=reset]")
        await page.wait_for_timeout(300)
        check(await page.locator("text=Welcome to PawSteps").count()==1,"reset returns to onboarding")
        # import restores
        await page.goto(URL)
        await page.fill("#f-name","Temp"); await page.click("[data-act=age][data-v=adult]"); await page.click("[data-act=onb-save]")
        await page.click(".nav [data-r=settings]")
        await page.set_input_files("#import-file", path)
        await page.wait_for_timeout(500)
        check((await page.locator(".day-hero h1").inner_text())=="Day 4 with Biscuit","import restores Biscuit")
        check((await page.locator("#sess-count").inner_text())=="2/3 done","import restores sessions")
        print("console:",console)
        check(not console,"no console errors/warnings")
        await b.close()
    print("\nFAILURES:",errors if errors else "none")
asyncio.run(main())
