DAYS.push(
{skill:"rollover", trick:true, title:"Trick Day: Roll Over", goal:"{dog} does a full roll from a down with a hand signal.",
 why:"Roll over teaches you to break a big behavior into small steps — a key trainer skill. Skip it or keep it partial for seniors or dogs with back or joint problems, and don’t practice right after meals.",
 need:[T,POUCH,"Soft surface (rug or grass)"], sessions:3, minutes:4, reps:"5–6 reps per session",
 steps:["Start with {dog} in a down on a soft surface.","Move a treat from their nose toward their shoulder, so their head turns back and they shift onto one hip. Mark “Yes!” and treat.","Continue the lure over their shoulder blade so they roll onto their side. Mark and treat.","Continue the lure so they roll onto their back and over to the other side. Mark and treat when they complete the roll. It’s fine to take several sessions to get here.","Fade the lure into a rolling hand motion, then add the cue “Roll over”."],
 success:["{dog} completes a full roll from a down with a hand signal, 3 out of 5 times."],
 mistakes:["Rushing the steps or pushing {dog} over.","Practicing on a hard floor.","Practicing right after a big meal."],
 levelUp:"Try the verbal cue only."},
{skill:null, review:true, combo:true, skills:["sit","down","touch","spin","place","stay"], title:"Combining Skills: Sequences", goal:"{dog} completes a 3-cue sequence in random order before getting a reward.",
 why:"Real life rarely uses one cue at a time. Sequences build fluency and teach {dog} to listen instead of guessing what comes next.",
 need:[T,POUCH,MAT], sessions:3, minutes:5, reps:"6–8 sequences per session",
 steps:["Start with 2 cues before a reward, like “Sit” → “Down” → “Yes!” + treat.","Move up to 3 cues: e.g. Touch → Sit → Spin → “Yes!” + treat.","Mix up the order every time so {dog} can’t anticipate.","Try a ‘mat routine’: Place → Down → 10-second stay → “Free!” → Touch.","If {dog} guesses wrong, don’t say “no” — just pause, then repeat the cue once or make the sequence shorter."],
 success:["{dog} completes a 3-cue sequence in random order before the reward, 4 out of 5 times."],
 mistakes:["Chains that are too long too soon.","Always using the same order — {dog} will start anticipating."],
 levelUp:"Create a 5-cue routine and show it off to family or friends."},
{skill:"wait", title:"Wait: Thresholds, Cars & Bowls", goal:"{dog} waits at 3 different thresholds until released.",
 why:"Generalizing ‘wait’ to cars, gates, curbs and food bowls keeps {dog} safe everywhere — not just at the front door.",
 need:[LEASH,HARN,"{dog}’s food bowl",T,POUCH], sessions:3, minutes:5, reps:"3–4 reps per threshold",
 steps:["Warm up with 3 waits at the front door.","Car: with {dog} safely in the car (harness or crate), open the door, say “Wait”, attach the leash, then release with “Free!” to hop out (or lift smaller or older dogs out).","Food bowl: say “Wait” and slowly lower the bowl. If {dog} moves toward it, raise it back up. When it reaches the floor with {dog} waiting, release with “Free!” to eat.","Curbs: on a walk, ask for a wait at each curb before crossing.","Gates and stairs: ask for a wait at the top of the stairs or at a gate before going through."],
 success:["{dog} waits at 3 different thresholds until released."],
 mistakes:["Letting the door opening or the bowl touching the floor become the release, instead of your word.","Making the bowl wait too long — a few seconds is plenty."],
 levelUp:"Practice wait at a busier door, like a store or friend’s house entrance."},
{skill:"focus", skills:["focus","name","touch"], title:"Field Trip: Focus in New Places", goal:"{dog} responds to their name and hand target in a new public place.",
 why:"Taking skills on the road is the real test. Short, positive outings teach {dog} that they can listen to you anywhere.",
 need:["Very high-value treats",POUCH,LEASH,HARN,"Water"], sessions:2, minutes:10, reps:"Short and positive",
 steps:["Pick a moderately busy place: the edge of a park, a quiet pet-friendly store, or a parking lot at a quiet time.","Let {dog} look around and sniff for 2–3 minutes before asking for anything.","Play the Name Game and reward every voluntary check-in.","Ask for easy behaviors: hand touch, sit. Reward generously.","Keep it short and leave on a success. Watch for stress signals (lip-licking, yawning, whale eye, refusing food) and move farther away if you see them."],
 success:["{dog} responds to name and touch, 4 out of 5 times, in a new public place."],
 mistakes:["Staying too long, or choosing somewhere too busy for a first trip.","Asking for hard behaviors before {dog} has had a chance to settle in."],
 levelUp:"Visit a slightly busier spot next time."},
{skill:"touch", title:"Hand Target as a Life Tool", goal:"{dog} moves to your hand on cue, even past a mild distraction.",
 why:"Touch becomes a handy everyday tool: getting off furniture, moving past distractions, and coming back to you.",
 need:[T,POUCH,LEASH,"A sticky note"], sessions:3, minutes:4, reps:"8–10 reps per session",
 steps:["Warm up with 5 quick touches.","Use touch to move {dog}: off the couch, into position beside you, or through a doorway.","Use touch as a mini-recall from across the room.","On a walk, use “Touch” to redirect {dog} away from a distraction, then reward.","Bonus: put a sticky note on your palm, then move it to a wall or door so {dog} learns to target an object (great for future tricks like closing doors)."],
 success:["{dog} moves to your hand on cue past a mild distraction, 4 out of 5 times."],
 mistakes:["Only using touch when something is wrong — keep it fun and rewarding.","Holding your hand out too long."],
 levelUp:"Teach {dog} to touch a sticky note on a cabinet door to close it."},
{skill:"settle", title:"Settle Anywhere: Café or Park Bench", goal:"{dog} relaxes on a mat for 10 minutes in a public place.",
 why:"Being able to relax out in the world opens up cafés, patios and visits with friends. The mat you’ve trained at home travels with you.",
 need:[MAT,"Long-lasting chew",T,LEASH,"Water"], sessions:1, minutes:15, reps:"One calm outing",
 steps:["Exercise {dog} first with a sniffy walk.","Pick a quiet outdoor café or park bench, away from foot traffic. Put down {dog}’s familiar mat and sit.","Reward any calm behavior with treats placed quietly between their paws.","Offer a long-lasting chew to help {dog} relax.","Stay 10–15 minutes and leave before {dog} gets restless."],
 success:["{dog} settles on the mat for 10 minutes in a public place."],
 mistakes:["Picking a busy spot for the first try.","Skipping exercise beforehand.","Staying until {dog} is overwhelmed or bored."],
 levelUp:"Build to 20 minutes, or try a slightly busier spot."},
{skill:null, review:true, graduation:true, skills:["name","focus","touch","sit","down","recall","leaveit","dropit","lll","stay","place","wait","settle","greet","crate","spin","paw","rollover"], title:"Graduation Day: Skills Check", goal:"Celebrate how far {dog} has come and plan your ongoing training.",
 why:"Training is a lifelong conversation. Today you celebrate progress, see the big picture, and set up a simple routine to keep skills sharp.",
 need:["High-value treats",POUCH,LEASH,MAT,"A helper or camera (optional)"], sessions:2, minutes:10, reps:"One run-through of each skill",
 steps:["Run through each skill once: name, look, touch, sit, down, come, leave it, drop it, loose-leash walk, stay, place, wait, settle, greeting, and your tricks.","Mark the skills that are reliable as mastered in this app (Progress → Skills).","Pick 2–3 skills to keep working on, and build them into everyday life (sit before meals, wait at doors, place during dinner).","Plan about 5 minutes of training a day to keep skills sharp, and keep rewarding good choices.","Celebrate! A special chew, a new toy, or a favorite outing. Take a photo of your graduate."],
 success:["You’ve tested every skill and marked the reliable ones as mastered.","You have a simple maintenance plan for the coming weeks."],
 mistakes:["Stopping rewards altogether — keep reinforcing, even if it’s less often.","Thinking ‘done’ means done. Skills fade without practice."],
 levelUp:"Look into a fun next step: a force-free class in tricks or nose work, or the AKC Canine Good Citizen test."}
);
DAYS.forEach((d,i)=>{ d.day=i+1; d.week=Math.floor(i/7)+1; if(!d.skills) d.skills=d.skill?[d.skill]:[]; });
