DAYS.push(
{skill:"wait", title:"Wait at Doors", goal:"{dog} waits while the door opens fully, until you release them.",
 why:"Door-dashing is one of the most common ways dogs get lost or hit by cars. ‘Wait’ means ‘pause here until I invite you’ — a brief pause, unlike a longer stay.",
 need:[LEASH,T,POUCH,"An interior door to practice on"], sessions:3, minutes:4, reps:"6–8 reps per session",
 steps:["Start at an interior door (or an exterior door with the leash on). Ask for a sit or just let {dog} stand.","Put your hand on the doorknob. If {dog} stays put, mark “Yes!” and treat. If they move forward, take your hand away.","Open the door an inch. If {dog} holds position, close it, mark and treat. If they move toward the gap, gently close the door (never on {dog}).","Gradually open it wider and keep it open longer.","Release with “Free!” or “Let’s go” and walk through together. Add the word “Wait” once {dog} is getting it."],
 success:["{dog} waits while the door opens fully, and until released, 4 out of 5 times."],
 mistakes:["Letting the door opening become the release — only your release word means go.","Practicing at a front door with no leash before the skill is solid.","Closing the door hard toward {dog} — it should be a gentle ‘oops, closed’."],
 levelUp:"Ask {dog} to wait while you step through first, then release them."},
{skill:"place", title:"Go to Place (Mat)", goal:"From 3 feet away, {dog} goes to the mat and lies down on cue.",
 why:"Place gives {dog} a clear, rewarding job when life gets busy — dinner time, the doorbell, visitors — instead of begging or jumping.",
 need:[MAT,T,POUCH], sessions:3, minutes:5, reps:"8–10 reps per session",
 steps:["Put a mat on the floor. Toss a treat onto it; when {dog} steps on, mark “Yes!” and drop another treat on the mat. Toss a treat off the mat to reset.","Now wait for {dog} to step onto the mat on their own. Mark and treat ON the mat.","Raise the bar: reward for all four paws on the mat, then for a sit or down on the mat.","Say “Place” as {dog} is heading to the mat. Soon you can say it first.","Build a little duration by dropping treats calmly between their paws while they lie there, then release with “Free!”. Gradually send from farther away."],
 success:["From 3 feet away, {dog} goes to the mat and lies down on cue, 4 out of 5 times."],
 mistakes:["Luring onto the mat for too long instead of letting {dog} offer it.","Delivering treats off the mat — rewarding on the mat builds its value.","Using the mat for time-outs."],
 levelUp:"Send {dog} from 6 feet away, or move the mat to a new room."},
{skill:"stay", title:"Stay, Part 2: Distance", goal:"{dog} holds a stay while you walk 10 feet away and come back.",
 why:"Now we add the second D — distance. We make duration easy again so {dog} only has one hard thing to think about.",
 need:[T,POUCH,QUIET], sessions:3, minutes:5, reps:"8–10 stays per session",
 steps:["Warm up with a few 10-second stays right in front of {dog}.","Ask for a stay, take ONE step back, then immediately step back in. Mark “Yes!”, treat in position, then release “Free!”.","Next try two steps, then three. Mix in easy reps (one step) between harder ones.","Always walk back to {dog} to reward. Don’t call them out of a stay — that blurs stay and recall.","Build to 5–10 steps. Try stepping sideways or turning your back for a second."],
 success:["{dog} holds a stay while you walk 10 feet away and back, 4 out of 5 times."],
 mistakes:["Increasing distance AND duration at the same time.","Calling {dog} to you from the stay.","Leaning or looming as you return — stay relaxed and upright."],
 levelUp:"Step out of sight around a doorway for 2 seconds and come straight back."},
{skill:"greet", title:"Polite Greetings: Four on the Floor", goal:"{dog} keeps four paws on the floor while a helper approaches and says hi.",
 why:"Jumping is a friendly attempt to say hello up close. Rather than punishing it, we show {dog} that keeping paws on the floor is what earns attention.",
 need:[LEASH,T,POUCH,"A helper"], sessions:3, minutes:5, reps:"5–8 approaches per session",
 steps:["Hold {dog}’s leash (or tether it to something sturdy) so they can’t practice jumping.","Your helper walks toward {dog}. As long as all four paws stay on the floor (or {dog} sits), the helper keeps coming and you mark “Yes!” and treat.","If {dog} jumps, the helper calmly turns away and steps back out of reach. Try again when {dog} is calmer.","When the helper reaches {dog}, they greet calmly and low — a chin scratch — while you scatter a few treats on the floor to keep {dog}’s head down.","When YOU come home, greet {dog} calmly and toss treats on the floor before jumping has a chance to happen."],
 success:["{dog} keeps four paws on the floor while the helper greets, 4 out of 5 approaches."],
 mistakes:["Pushing {dog} down, kneeing them or stepping on paws — these are aversive and still give attention.","Inconsistency — if some family members allow jumping, {dog} will keep trying.","Greeting when {dog} is over-excited. Wait for a calmer moment."],
 levelUp:"Ask your helper to be a little more excited when they say hi."},
{skill:"lll", title:"Loose-Leash Walking: Taking It Outside", goal:"{dog} walks 20 steps on a loose leash in a quiet outdoor area.",
 why:"Outdoors is full of smells and sights, so it’s much harder than the living room. We go back to frequent rewards and add sniffing as a reward.",
 need:[LEASH,HARN,"High-value treats",POUCH], sessions:2, minutes:8, reps:"Reward every few steps",
 steps:["Start somewhere low-distraction (driveway, quiet street) at a quiet time of day.","Reward {dog} frequently in the reward zone — every few steps at first. Outdoor treats need to be extra tasty.","Practice changes of direction: say “This way!” cheerfully, turn, and reward when {dog} catches up.","If the leash tightens, stop and wait for slack, then walk on.","Use sniffing as a reward: after some nice walking, say “Go sniff!” and let {dog} explore for 10–20 seconds."],
 success:["{dog} walks 20 steps on a loose leash in a quiet outdoor area, 3 out of 4 tries."],
 mistakes:["Expecting indoor-level skills outside on day one.","Making training walks too long. Separate short training walks from relaxed ‘sniffari’ walks on a long line.","Using a retractable leash or yanking the leash."],
 levelUp:"Walk past a mildly interesting spot (a hedge, a mailbox) with a loose leash."},
{skill:"recall", title:"Recall Games: Round Robin & Hide-and-Seek", goal:"{dog} comes on the first call during a game, even with a mild distraction around.",
 why:"Games build speed and enthusiasm. The more fun recall is, the more reliable it gets.",
 need:["High-value treats",POUCH,"A helper","A toy for distraction","15–30 ft long line (outdoors)"], sessions:3, minutes:4, reps:"6–8 recalls per session",
 steps:["Round robin: two or more people stand across a room or fenced yard, each with treats. Take turns calling “{dog}, come!”, with a jackpot and a collar touch each time.","Hide-and-seek: while {dog} is distracted, hide behind a door or furniture and call once. Celebrate big when they find you.","Add a mild distraction, like a toy lying on the floor, and call {dog} past it.","Practice outdoors only in a securely fenced area or with a long line attached to a harness.","Keep it short and finish while {dog} is still eager."],
 success:["{dog} comes on the first call during round robin with a mild distraction, 8 out of 10 times."],
 mistakes:["Calling more than once.","Ending the fun every time you call. Release {dog} back to play often.","Practicing off-leash in an unfenced area."],
 levelUp:"Call {dog} while they’re sniffing something mildly interesting."},
{skill:null, review:true, skills:["wait","place","stay","greet","lll","recall"], title:"Review Day: Week 3 Self-Control", goal:"Combine doors, mats, stays and greetings in short, upbeat sessions.",
 why:"Week 3 skills are all about calm self-control. Reviewing them together shows {dog} that the same rules apply in different situations.",
 need:[T,POUCH,LEASH,MAT,"A helper (optional)"], sessions:3, minutes:5, reps:"Mix all skills in each session",
 steps:["Wait at an interior door 3 times, opening it a little wider each time.","Send {dog} to place 3 times and reward calm lying down.","Do 3 stays: one for duration (20 seconds), one for distance (10 feet), and one easy one.","If you have a helper, practice 3 four-on-the-floor greetings.","Finish with a recall game and a sniff break."],
 success:["{dog} meets the success criteria for at least 4 of the 6 skills.","You’ve noted which skill to repeat or practice more."],
 mistakes:["Stacking difficulty (long stay + far distance) on a review day."],
 levelUp:"Chain them: wait at the door → walk to the mat → place → stay for 20 seconds."}
);
