DAYS.push(
{skill:"stay", title:"Stay, Part 3: Distraction", goal:"{dog} holds a stay while you drop a toy on the floor 2 feet away.",
 why:"Distraction is the third D, and the one real life throws at you most. Start tiny and build up.",
 need:[T,POUCH,"A toy or ball"], sessions:3, minutes:5, reps:"8–10 stays per session",
 steps:["Warm up with a few short stays close to {dog}.","Add tiny distractions while standing close: shift your weight, raise an arm, bend your knees. Mark “Yes!” and treat for holding.","Progress gradually: clap once, drop a glove, bounce a ball once.","Drop a toy, then release {dog} with “Free — get it!” as a bonus reward. Getting the toy becomes the payoff for staying.","Only combine Ds (a bit of distance AND a distraction) once each D is solid alone."],
 success:["{dog} holds a stay while you drop a toy 2 feet away, 4 out of 5 times."],
 mistakes:["Big jumps in difficulty — tiny steps are faster in the long run.","Scolding when {dog} breaks. Just reset and make it easier.","Rewarding after the release instead of in position."],
 levelUp:"Hold a stay while a recorded doorbell sound plays quietly."},
{skill:"leaveit", title:"Leave It: On the Floor & On the Move", goal:"{dog} walks past a treat on the floor on a loose leash.",
 why:"Real-world ‘leave it’ happens on walks, with things on the ground. Now we move the skill from your hand to the floor and add movement.",
 need:[T,"Higher-value treats",POUCH,LEASH], sessions:3, minutes:5, reps:"6–8 reps per session",
 steps:["Warm up with the closed-fist and open-palm versions.","Place a treat on the floor and cover it with your hand. When {dog} looks away, mark “Yes!” and reward from your other hand.","Uncover the treat while standing, with your foot ready to cover it if {dog} goes for it.","With {dog} on leash, walk past a treat on the floor at a distance where they can succeed. Say “Leave it” and reward when they look at you.","Gradually walk closer. Keep the leash short enough to prevent grabbing — management, never jerking."],
 success:["{dog} walks past a treat on the floor 3 feet away with a loose leash, 4 out of 5 times."],
 mistakes:["Leash pops or jerks.","Getting too close too fast.","Leaving truly dangerous items accessible — use management while training."],
 levelUp:"Practice leave it with a toy, or with a food wrapper on a walk."},
{skill:"spin", trick:true, title:"Trick Day: Spin", goal:"{dog} spins in a circle with a small hand signal.",
 why:"Tricks keep training fun and build your timing and {dog}’s confidence. Spin is a quick win for almost every dog.",
 need:[T,POUCH,"Non-slip floor"], sessions:3, minutes:3, reps:"5–8 spins per session",
 steps:["Hold a treat at {dog}’s nose and slowly lure them in a wide circle at nose height.","Mark “Yes!” as they complete the full circle, then treat.","After 5 lured reps, use the same motion with an empty hand and reward from your other hand.","Gradually shrink the motion to a small circle with your finger.","Add the word “Spin” before the hand signal. Teach the other direction with a different word, like “Twirl”."],
 success:["{dog} spins in one direction with a small hand signal, 4 out of 5 times."],
 mistakes:["Luring too fast or too high, so {dog} loses the treat or jumps.","Too many reps — spinning can make dogs dizzy. Keep it short."],
 levelUp:"Teach the opposite direction, or cue a spin from a few feet away."},
{skill:"settle", title:"Settle: Relaxing on Cue", goal:"{dog} relaxes on a mat for 5 minutes while you read.",
 why:"Calm is a skill. Rewarding relaxation teaches {dog} an ‘off switch’ for busy homes, vet waiting rooms and cafés.",
 need:[MAT,T,"A book or your phone","Long-lasting chew (optional)"], sessions:2, minutes:10, reps:"Calm, spaced-out rewards",
 steps:["Make sure {dog} has had some exercise and a sniff first. Put the mat by your chair and sit down with a book.","Ignore busy behavior. When {dog} lies down, quietly place a treat between their paws. Use a soft, low “good” instead of an excited “Yes!”.","Reward signs of relaxation: hips rolled to one side, head resting down, a big sigh.","Gradually wait longer between treats — 10 seconds, 30 seconds, a minute.","Once {dog} is reliably relaxing, add the cue “Settle” as they lie down. Also reward calmness you notice during the day (capturing)."],
 success:["{dog} relaxes on the mat for 5 minutes while you read, in 2 out of 2 sessions."],
 mistakes:["Delivering treats with excitement, which winds {dog} up.","Expecting calm from an under-exercised dog.","Sessions that drag on — stop while {dog} is still relaxed."],
 levelUp:"Practice settle while the TV is on or family members walk by."},
{skill:"sit", skills:["sit","down"], title:"Sit & Down Anywhere (Generalization)", goal:"{dog} sits and lies down on a verbal cue alone in 3 different places.",
 why:"Dogs don’t generalize well — ‘sit in the kitchen’ and ‘sit on the porch’ feel like different skills. Practicing in new places makes cues reliable.",
 need:[T,POUCH,LEASH], sessions:3, minutes:5, reps:"5 sits + 5 downs per location",
 steps:["List 5 spots to practice: kitchen, hallway, yard, porch, and on a walk.","In each new place, start easy: use the hand signal, or even a lure for 1–2 reps.","Test the verbal cue alone: keep your hands still at your sides and say “Sit” once.","Change your position: try cues while sitting in a chair, kneeling, or with your side to {dog}.","Once {dog} is fluent, reward most (not every) correct response with a treat and the rest with praise or a game."],
 success:["{dog} sits and lies down on the verbal cue alone in 3 different locations."],
 mistakes:["Assuming {dog} is being stubborn — new places really are harder.","Repeating the cue. Make it easier instead.","Phasing out rewards too early."],
 levelUp:"Ask for a down while {dog} is standing 3 feet away from you."},
{skill:"crate", title:"Alone-Time: Building Duration", goal:"{dog} stays relaxed alone for 10 minutes with a chew.",
 why:"Gradually building alone time prevents stress and helps {dog} feel secure when you leave the house.",
 need:["Crate, pen or safe room","Long-lasting chew or stuffed food toy","Phone camera to watch (optional)"], sessions:2, minutes:15, reps:"3–4 departures per session",
 steps:["Desensitize departure cues: pick up your keys or put on shoes, then sit back down. Repeat until {dog} stops reacting.","Give {dog} a chew in their safe area. Leave the room for 30 seconds and return calmly. Then try 1, 2, then 5 minutes — and mix in short ones.","Watch {dog}’s body language (a phone camera helps). Relaxed? Progress. Whining, pacing or scratching? Shorten the time.","Keep returns boring: walk in, say a quiet hello, and let {dog} out once they’re calm.","Try a real mini-departure: step outside the front door for a minute and come back."],
 success:["{dog} stays relaxed alone for 10 minutes with a chew."],
 mistakes:["Big, emotional goodbyes and hellos.","Increasing time too fast.","Punishing accidents or destruction — they’re signs of stress, not spite."],
 levelUp:"Build to 20–30 minutes, only as long as {dog} stays relaxed."},
{skill:null, review:true, skills:["stay","leaveit","spin","settle","sit","down","crate"], title:"Review Day: Proofing Check-In", goal:"See how {dog}’s skills hold up with the 3 Ds and in new places.",
 why:"This review tests whether skills are truly proofed. It’s normal for a few to need more work — that’s useful information, not failure.",
 need:[T,"High-value treats",POUCH,LEASH,MAT,"A toy"], sessions:3, minutes:5, reps:"Mix all skills in each session",
 steps:["Do 3 stays: one long (30s), one with distance (10 ft), one with a distraction (toy drop).","Practice leave it with a treat on the floor, walking past on leash.","Show off spin 3 times.","Ask for sit and down with the verbal cue only, in a room you rarely train in.","End with 5–10 minutes of settle or crate time with a chew."],
 success:["{dog} meets the success criteria for most skills.","You’ve chosen 1–2 skills to repeat if needed."],
 mistakes:["Testing everything at maximum difficulty. Mix easy reps between hard ones."],
 levelUp:"Do the review outside in your yard or on a quiet street."}
);
