DAYS.push(
{skill:"paw", trick:true, title:"Trick Day: Shake / Paw", goal:"{dog} places a paw in your open palm on cue.",
 why:"Paw is a classic trick that also helps {dog} get comfortable with paw handling — handy for nail trims and vet visits.",
 need:[T,POUCH], sessions:3, minutes:3, reps:"6–8 reps per session",
 steps:["Ask {dog} to sit. Hold a treat in a closed fist, low, near their chest and paw height.","Many dogs will paw at your fist. The instant their paw lifts or touches your hand, mark “Yes!”, open your hand and let them have the treat.","Repeat, then present an open, flat palm (no treat in it). Mark the paw touch and reward from your other hand.","Add the cue “Paw” or “Shake” just before you present your hand.","Teach the other paw with a different cue, like “High five” with your palm facing {dog}."],
 success:["{dog} offers a paw into your open palm on cue, 4 out of 5 times."],
 mistakes:["Grabbing and lifting {dog}’s paw for them.","Holding your hand too high.","Rewarding pawing that isn’t cued — this can become demand-pawing."],
 levelUp:"Teach a ‘high five’ with the other paw."},
{skill:"recall", title:"Recall Outdoors on a Long Line", goal:"{dog} comes from 15+ feet away outdoors, with moderate distractions, on the first call.",
 why:"Outdoor recall is where it really counts. A long line gives {dog} freedom to explore while keeping them safe as you practice.",
 need:["15–30 ft long line",HARN,"Very high-value treats",POUCH], sessions:2, minutes:8, reps:"5–6 recalls per session",
 steps:["Attach a 15–30 ft long line to a back-clip harness (never a collar — sudden stops can injure the neck). Let it trail or hold it loosely.","Let {dog} explore. When they’re mildly interested in something (but not glued to it), call once: “{dog}, come!”.","When they come: jackpot, party, then release them to go sniff again with “Go sniff!”.","If they don’t come, don’t repeat the cue. Move away, make a fun noise, or crouch down. If needed, calmly walk up the line — don’t reel them in. Make the next rep easier.","Optional: charge a special ‘emergency recall’ word (like “Pizza!”) paired only with the very best treats, and save it for emergencies."],
 success:["{dog} comes on the first call from 15+ feet away outdoors, 8 out of 10 times."],
 mistakes:["Wrapping the long line around your hand — wear gloves and hold it loosely to avoid rope burns.","Calling when {dog} is fixated (squirrel!). Set up wins instead.","Going off-leash in unfenced areas too soon."],
 levelUp:"Practice your emergency recall word at random times in the house and yard."},
{skill:"place", title:"Place with Real-Life Distractions", goal:"{dog} stays on the mat while someone knocks and the door opens.",
 why:"Place is most valuable when life is chaotic. Today we build it up step by step for the moments you need it most.",
 need:[MAT,"High-value treats",POUCH,"A helper (or a doorbell sound on your phone)",LEASH], sessions:3, minutes:5, reps:"5–8 reps per session",
 steps:["Warm up: send {dog} to place and build to 30–60 seconds, calmly dropping treats on the mat.","Add household distractions: walk around, open the fridge, knock lightly on a table. Reward {dog} for staying.","Play a recorded doorbell or knock at low volume. Reward generously for staying on the mat.","With a helper: they knock or ring, you send {dog} to place, and reward. Then open the door and let the helper come in calmly.","Use a leash or gate as backup if needed — management is not failure."],
 success:["{dog} stays on place while someone knocks and the door opens, 3 out of 5 times."],
 mistakes:["Jumping straight to the real doorbell with excited guests.","Expecting {dog} to stay for long periods without any reinforcement."],
 levelUp:"Ask {dog} to place while you eat dinner."},
{skill:"lll", title:"Loose-Leash Walking Past Distractions", goal:"{dog} walks past a moderate distraction 20 feet away with a loose leash.",
 why:"Other dogs, squirrels and people are the toughest leash challenges. Working at the right distance lets {dog} learn instead of react.",
 need:[LEASH,HARN,"Very high-value treats",POUCH], sessions:2, minutes:8, reps:"Several passes per session",
 steps:["Find {dog}’s threshold — the distance at which they notice a distraction but can still take food and respond to you.","Play ‘Look at That’: when {dog} looks at the distraction, mark “Yes!” and treat. Seeing the distraction starts to predict good things from you.","Practice U-turns: say “This way!” cheerfully and turn away from anything too exciting. Reward when {dog} follows.","Walk past distractions at a comfortable distance and slowly reduce it over many sessions. Use sniff breaks as rewards.","If {dog} goes over threshold (lunging, barking, refusing food), calmly add distance. It’s not defiance — it means it’s too hard right now."],
 success:["{dog} walks past a moderate distraction at about 20 feet with a loose leash, 3 out of 4 times."],
 mistakes:["Getting too close too fast.","A tight leash, which adds tension and can increase reactivity.","Corrections or leash pops. ⚠️ If {dog} regularly lunges or barks at dogs or people, work with a force-free professional."],
 levelUp:"Reduce the distance to the distraction by a few feet."},
{skill:"greet", title:"Polite Greetings with Visitors", goal:"{dog} greets 2 visitors without jumping.",
 why:"Real visitors arriving is peak excitement. We practice the whole arrival routine so it becomes calm and predictable.",
 need:[LEASH,"Baby gate (optional)",MAT,T,"1–2 helpers"], sessions:2, minutes:8, reps:"5 arrivals per session",
 steps:["Plan your management: leash or baby gate ready before the visitor arrives.","When the visitor knocks, send {dog} to place or hold the leash.","The visitor enters and ignores {dog} at first. When {dog} has four on the floor or is calm, the visitor greets calmly and low, or tosses a treat on the floor.","Have the visitor leave and come back 5 times. Repeated arrivals quickly become boring (in a good way).","On walks, ask {dog} for a sit or hand target when a person stops to say hi."],
 success:["{dog} greets 2 different visitors without jumping."],
 mistakes:["Visitors saying “I don’t mind!” and encouraging jumping — brief them first.","Too many people arriving at once.","Forcing greetings — not every dog wants to say hi to strangers, and that’s okay."],
 levelUp:"Practice with a visitor {dog} finds really exciting."},
{skill:"dropit", skills:["dropit","leaveit"], title:"Impulse Control Games: Drop, Leave & Trade", goal:"{dog} drops a tug toy mid-game on cue and leaves a tossed toy until released.",
 why:"Combining drop it and leave it in play teaches {dog} that self-control and fun go together.",
 need:["Tug toy","Another toy or ball",T,POUCH], sessions:3, minutes:4, reps:"6–8 reps per session",
 steps:["Tug with rules: invite {dog} to tug with “Take it”, play for 10–20 seconds, then say “Drop” and freeze the toy (hold it still against your body). Mark and reward the drop.","Restart the game with “Take it” — restarting is the biggest reward.","Toss a toy, say “Leave it”, and reward when {dog} holds back. Then release with “Get it!”.","Set up a ‘found item’ on a walk (a toy you planted earlier) and practice “Drop” with a trade.","Keep the energy fun but under control — if {dog} gets too wild, pause until they calm down."],
 success:["{dog} drops a tug toy mid-play on cue, 4 out of 5 times.","{dog} leaves a tossed toy until released, 3 out of 5 times."],
 mistakes:["Letting tug get frantic or mouthy — pause the game for calm.","Ending every game by taking the toy away for good."],
 levelUp:"Drop → sit → “Take it” as one smooth sequence."},
{skill:null, review:true, skills:["paw","recall","place","lll","greet","dropit","leaveit"], title:"Review Day: Combining Skills", goal:"Run through week 5 skills in real-life setups.",
 why:"By now {dog} has a big toolbox. This review checks that skills hold up with real distractions.",
 need:["High-value treats",POUCH,LEASH,"Long line",MAT,"Tug toy"], sessions:3, minutes:6, reps:"Mix all skills in each session",
 steps:["Show off paw 3 times.","Do 3 long-line recalls outdoors.","Practice place while someone knocks on the door.","Take a short loose-leash walk with a ‘Look at That’ moment.","Play a round of tug with 3 drops, then a leave-it with a toy."],
 success:["{dog} meets the success criteria for most week-5 skills.","You’ve noted which skills need extra practice."],
 mistakes:["Doing everything in one long session — split it across the day."],
 levelUp:"Try the review at a friend’s house or a quiet park."}
);
