DAYS.push(
{skill:"recall", title:"Come! Recall Basics", goal:"{dog} runs to you happily from across a quiet room on the first call.",
 why:"A reliable recall can save {dog}’s life. We build it as the best game in the world, so coming to you is always worth it.",
 need:["High-value treats (chicken, cheese)",POUCH,"A helper (optional)"], sessions:3, minutes:3, reps:"5–6 recalls per session",
 steps:["Pick a cue that has no bad history. If “Come” has been yelled a lot, choose “Here!” instead.","Charge the cue: with {dog} next to you, say “{dog}, come!” cheerfully and immediately give a treat at your feet. Repeat 5 times.","Back-up recall: when {dog} is a few feet away, call once, then clap and jog backwards. Mark “Yes!” as they reach you and give a jackpot — 3–5 treats one at a time.","Gently touch {dog}’s collar or harness before treating, so being caught is also a good thing.","Release with “Free!” to go back to playing — coming to you shouldn’t always end the fun. Gradually call from farther across the room."],
 success:["{dog} comes immediately from across a quiet room, 9 out of 10 times."],
 mistakes:["Calling {dog} for something unpleasant (bath, nail trim, leaving the park). Go get them instead.","Repeating the cue. Call once, then help with movement and noise.","Chasing {dog} — it turns into a game of keep-away.","Calling when you know they won’t come. Set up only recalls you’re confident will work."],
 levelUp:"Call {dog} from another room, or play ‘puppy ping-pong’ with a family member."},
{skill:"leaveit", title:"Leave It: The Closed Fist", goal:"{dog} turns away from a treat in your open palm when you say “Leave it”.",
 why:"Leave it is a life-saving skill for dropped pills, chicken bones and trash. It also teaches {dog} that self-control pays off.",
 need:["Two kinds of treats: a ‘boring’ one to leave and a better one to reward",POUCH], sessions:3, minutes:4, reps:"8–10 reps per session",
 steps:["Put a treat in a closed fist and hold it near {dog}. They’ll sniff, lick or paw — keep your fist closed and stay silent.","The moment {dog} backs off or looks away, mark “Yes!” and give a treat from your OTHER hand. Never give them the ‘leave it’ treat.","Repeat until {dog} immediately moves away from your fist.","Now say “Leave it” as you present the fist.","Progress to an open palm: if {dog} moves toward it, just close your hand. Reward from the other hand when they hold back."],
 success:["{dog} turns away from an open palm holding a treat when you say “Leave it”, 4 out of 5 times."],
 mistakes:["Giving {dog} the treat they were asked to leave — it teaches ‘leave it means wait a moment, then get it’.","Saying “leave it” repeatedly, or sternly. It’s just information.","Moving to the floor before the open palm is solid."],
 levelUp:"Place a treat on the floor and cover it with your hand. Reward when {dog} looks away from your hand."},
{skill:"dropit", title:"Drop It: The Trade Game", goal:"{dog} lets go of a toy when you say “Drop” — before they see the treat.",
 why:"Drop it is safer than prying things out of {dog}’s mouth. Because {dog} learns that letting go pays (and often gets the item back), they’re less likely to run off or guard things.",
 need:["A low-value toy","High-value treats",POUCH], sessions:3, minutes:4, reps:"6–8 trades per session",
 steps:["Offer a low-value toy and let {dog} play with it for a few seconds.","Put a high-value treat right at {dog}’s nose. As they open their mouth to take it, say “Drop”, then mark “Yes!” and give the treat.","Give the toy BACK. This is the secret — dropping doesn’t mean losing.","Repeat 5–8 times. Then say “Drop” first, wait 2 seconds, and only then show the treat.","In everyday life, trade up for anything {dog} picks up instead of chasing."],
 success:["{dog} drops a low-value toy on the verbal cue before seeing the treat, 4 out of 5 times."],
 mistakes:["Chasing {dog} to get things back — this teaches keep-away.","Prying their mouth open or grabbing the item.","Always taking the item away. Return it most of the time when it’s safe.","Using a treat that’s less exciting than the toy.","⚠️ If {dog} growls, freezes or guards items, stop and consult a force-free trainer or veterinary behaviorist."],
 levelUp:"Play tug and pause with a “Drop” every 20 seconds — restarting the game is the reward."},
{skill:"lll", title:"Loose-Leash Walking: The Reward Zone", goal:"{dog} walks 10 steps indoors beside you on a loose leash.",
 why:"Pulling is learned because it works — it gets dogs where they want to go. We teach that the spot next to your leg is where all the good stuff happens.",
 need:[LEASH,HARN,T,POUCH], sessions:3, minutes:5, reps:"Reward every 1–3 steps",
 steps:["Choose a side (left or right). The ‘reward zone’ is right next to your leg on that side.","Indoors, with the leash on and loose, take a step. When {dog} is beside you, mark “Yes!” and deliver the treat right at your leg seam, low down.","Walk a few steps, rewarding very often (every 1–2 steps at first) for being in the zone.","If {dog} forges ahead and the leash tightens, stop and ‘be a tree’. The moment the leash slackens or they look back, mark, treat at your side, and walk on.","Gradually increase the number of steps between rewards: 2, 3, 5, then 10."],
 success:["{dog} walks 10 steps indoors with a loose leash, 4 out of 5 tries."],
 mistakes:["Pulling back or jerking the leash — it creates tension and makes dogs pull harder.","Letting pulling work ‘just this once’.","Delivering treats out in front of you, which draws {dog} ahead.","Using a retractable leash, which teaches dogs that pulling extends the leash."],
 levelUp:"Practice in the backyard or driveway."},
{skill:"stay", title:"Stay, Part 1: Duration", goal:"{dog} holds a sit-stay for 15–20 seconds while you stand right in front of them.",
 why:"Stay is built with the 3 Ds — Duration, Distance and Distraction — one at a time. Today we work on duration only.",
 need:[T,POUCH,QUIET], sessions:3, minutes:5, reps:"8–10 stays per session",
 steps:["Teach a release word first: ask for a sit, say “Free!” and toss a treat a step away so {dog} gets up. Repeat 3 times — “Free!” means ‘you can move now’.","Ask for a sit. Say “Stay” with a flat palm toward {dog}, wait 1 second, mark “Yes!”, and give a treat while {dog} is still sitting. Then say “Free!”.","Build time in a ping-pong pattern: 2s, 3s, 1s, 5s, 3s, 8s, 2s, 10s… Varying it keeps it easy to succeed.","If {dog} gets up, calmly reset with no fuss, and make the next rep shorter.","Stay right in front of {dog} — no distance today. (Some trainers skip the word “Stay” and treat every cue as ‘hold it until released’. Both approaches work.)"],
 success:["{dog} holds a sit-stay for 15–20 seconds with you standing in front, 4 out of 5 times."],
 mistakes:["Rewarding after the release — the treat must come while {dog} is still in position.","Increasing time too quickly or always making it harder.","Forgetting to release, so {dog} learns to decide when stay ends.","Adding distance too soon."],
 levelUp:"Build to 30 seconds, or practice the same thing in a down."},
{skill:"crate", title:"Crate & Alone-Time Comfort", goal:"{dog} walks into the crate on their own and relaxes with a chew for 5 minutes, door closed, you nearby.",
 why:"A crate or safe space should feel like a cozy den, never a punishment. Gradual practice prevents stress and builds a dog who can relax when alone.",
 need:["Crate, pen or gated area","Soft bedding","Long-lasting chew or stuffed food toy",T], sessions:2, minutes:10, reps:"Short, relaxed reps",
 steps:["Make the crate cozy: soft bedding, in a living area, with the door secured open so it can’t swing and bang.","Toss treats near, then inside the crate. Let {dog} walk in and out freely — never push them in.","Feed a meal inside the crate with the door open.","Give a long-lasting chew in the crate and sit nearby. Close the door for a few seconds while they chew, and open it before they finish or fuss.","Build up to a few minutes with the door closed while you’re in the room, then step out of sight for a few seconds and return calmly. Keep departures and returns boring."],
 success:["{dog} goes in on their own and settles with a chew for 5 minutes, door closed, you in the room, with no distress."],
 mistakes:["Using the crate as punishment or a ‘time-out’.","Leaving {dog} too long too soon. If {dog} is crying or panicking, you’ve moved too fast — go back a step.","Making a big emotional fuss when you leave or come back.","Not every dog needs a crate — a gated room or pen works too. ⚠️ Drooling, destruction, howling or escape attempts when alone may be separation anxiety; talk to your vet or a certified separation anxiety trainer."],
 levelUp:"Step out of the room for 1–2 minutes while {dog} enjoys a chew."},
{skill:null, review:true, skills:["recall","leaveit","dropit","lll","stay","crate"], title:"Review Day: Week 2 Life Skills", goal:"Practice each week-2 skill and decide which ones need an extra day.",
 why:"Life skills get used every day. A review session helps them stick before we start adding distance and distractions.",
 need:[T,"High-value treats",POUCH,LEASH,"A toy"], sessions:3, minutes:5, reps:"Mix all skills in each session",
 steps:["Warm up with 3 back-up recalls.","Leave it with an open palm (3 reps), then 3 Drop-It trades with a toy.","Do 2 minutes of reward-zone loose-leash walking indoors.","Practice 3 sit-stays, ping-ponging between 5 and 20 seconds.","Finish with 5 minutes of relaxed crate time with a chew."],
 success:["{dog} does each skill at the level of its day’s success criteria.","You’ve noted any skill to repeat (use ‘Repeat this day’ on that lesson if needed)."],
 mistakes:["Skipping the weakest skill because it’s frustrating — that’s the one to practice (just make it easier)."],
 levelUp:"Do the whole review in your backyard or a quiet hallway."}
);
