DAYS.push(
{skill:"marker", title:"Charge Your Marker Word", goal:"Teach {dog} that “Yes!” (or a click) always means a treat is coming.",
 why:"Your marker is how you’ll talk to {dog} for the rest of the program. Once it predicts food, it becomes a powerful “that’s it!” signal that makes every new skill faster to learn.",
 need:[T,POUCH,CLICK,QUIET], sessions:3, minutes:3, reps:"10–15 reps per session",
 steps:["Prepare 15–20 tiny, soft treats and sit or stand in a quiet room with {dog}.","Say “Yes!” in a bright, consistent tone (or click once), then give a treat within 1–2 seconds.","Keep your hands still until AFTER the marker. The word — not your hand moving to the treat pouch — should be what predicts food.","Repeat 10–15 times at random intervals, whether {dog} is looking at you or not. {dog} doesn’t have to do anything yet.","Test it: when {dog} is mildly distracted (sniffing the floor), say “Yes!”. A quick head-whip toward you means the marker is charged."],
 success:["{dog} turns toward you immediately when they hear the marker, 4 out of 5 times.","{dog} looks expectant (perks up, looks at your hands or face) as soon as you mark."],
 mistakes:["Reaching for treats before saying the marker — the hand movement becomes the signal instead.","Using “Yes” in everyday conversation. If that’s hard for your household, choose a unique word like “Yip!” or use a clicker.","Marking without paying. Every marker = a treat, even if you marked by accident.","Shouting the marker. A clear, happy, normal voice is best."],
 levelUp:"Charge the marker in two other rooms, or charge a clicker as a second marker."},
{skill:"name", title:"The Name Game", goal:"{dog} whips their head toward you every time they hear their name.",
 why:"Their name is your attention-getter. If it reliably means ‘look at me, good things happen’, you can interrupt and redirect {dog} before you need any other cue.",
 need:[T,POUCH,QUIET], sessions:3, minutes:3, reps:"10 reps per session",
 steps:["Start close to {dog} in a quiet room, when they’re not busy with something else.","Say {dog}’s name once, in a happy voice.","The instant {dog} looks at you, mark “Yes!” and treat.","If they don’t look within 2 seconds, make a kissy noise or crouch down — don’t repeat the name. Mark and treat when they look.","Wait until {dog} looks away, then repeat. As they improve, say the name while you’re a few steps away or while they’re sniffing a toy."],
 success:["{dog} turns their head toward you within 1 second, 8 out of 10 times in a quiet room."],
 mistakes:["Repeating the name over and over — this teaches {dog} to tune you out.","Using their name when scolding or before unpleasant things (bath, nail trims). Go get {dog} instead.","Jumping to hard situations (squirrels!) too early. Build the habit in easy places first."],
 levelUp:"Say {dog}’s name from another room — reward when they come find you."},
{skill:"focus", title:"Eye Contact & Check-Ins", goal:"{dog} offers and holds soft eye contact for 3 seconds, even with food in view.",
 why:"Eye contact is the foundation of focus. A dog who checks in on their own is a dog who’s ready to listen — especially around distractions later on.",
 need:[T,POUCH,QUIET], sessions:3, minutes:4, reps:"8–10 reps per session",
 steps:["Hold a treat in your hand, out to the side at arm’s length. {dog} will probably stare at it — that’s fine. Stay silent and still.","Wait. The moment {dog} glances from the treat to your face, mark “Yes!” and give the treat.","Repeat until {dog} looks at your face quickly. Then wait for 1 second of eye contact before marking, then 2, then 3.","Once it’s reliable, say “Look” just before you hold your hand out.","Throughout the day, mark and reward any time {dog} checks in with you on their own (capturing)."],
 success:["{dog} holds eye contact for 3 seconds while you hold a treat out to the side, 4 out of 5 times."],
 mistakes:["Staring hard or leaning over {dog} — some dogs find direct staring uncomfortable. Keep soft eyes and blink.","Luring the treat to your face every time instead of waiting for {dog} to figure it out.","Saying “look, look, look”. Silence helps {dog} think."],
 levelUp:"Build to 5 seconds, or practice with a mild distraction like a toy on the floor."},
{skill:"touch", title:"Hand Target (Touch)", goal:"{dog} bumps their nose into your open palm when you say “Touch”.",
 why:"Touch is a quick, happy behavior you can use to move {dog} anywhere — and it’s a great confidence builder because it’s so easy to get right.",
 need:[T,POUCH,CLICK], sessions:3, minutes:4, reps:"10 reps per session",
 steps:["Present a flat open palm 2–3 inches from {dog}’s nose, at nose height.","Most dogs sniff it. The moment their nose touches your palm, mark “Yes!” and treat from your OTHER hand.","Hide the target hand behind your back, then present it again. Only leave it out 2–3 seconds each time.","If {dog} doesn’t sniff, rub a little treat scent on your palm, or move it slightly away (movement attracts attention).","After 8 out of 10 successes, say “Touch” just before presenting your hand. Then move your hand left, right, higher, lower and a little farther away."],
 success:["{dog} bumps your hand on cue 8 out of 10 times, even when it’s 1–2 feet away."],
 mistakes:["Pushing your hand into {dog}’s nose — let them come to you.","Leaving the hand out too long, which makes it boring.","Rewarding licks or mouthing instead of a clear nose bump."],
 levelUp:"Walk backward and have {dog} follow your hand for 3 touches in a row."},
{skill:"sit", title:"Sit", goal:"{dog} sits on a verbal cue or hand signal — no food in your signaling hand.",
 why:"Sit is a polite default behavior. It’s the building block for waiting at doors, greeting people nicely, and ‘saying please’.",
 need:[T,POUCH,QUIET], sessions:3, minutes:4, reps:"10 reps per session",
 steps:["Hold a treat right at {dog}’s nose. Slowly move it up and slightly back over their head.","As their head goes up, their rear will go down. Mark “Yes!” the instant their rear touches the floor, then give the treat.","Release with “Free!” and toss a treat a step away so {dog} stands up again. Repeat 5 times with food in your hand.","Now use the same hand motion with an EMPTY hand, and deliver the treat from your other hand or pouch. This fades the lure.","When {dog} sits reliably for the empty-hand signal, say “Sit” once, pause a beat, then give the hand signal. Soon the word alone will work."],
 success:["{dog} sits on the verbal cue or hand signal with no food in your signaling hand, 4 out of 5 times in a quiet room."],
 mistakes:["Pushing {dog}’s rear down — it’s unpleasant and doesn’t teach them to do it themselves.","Holding the lure too high, so {dog} jumps up to reach it.","Keeping food in the signaling hand for too long. Fade it after about 5 reps.","Repeating “sit, sit, sit”."],
 levelUp:"Ask for a sit before meals and before you open the door to go outside."},
{skill:"down", title:"Down", goal:"{dog} lies down on a hand signal with an empty hand.",
 why:"Down is a calmer, more stable position — the base for settling, longer stays, and relaxing at a café or the vet.",
 need:[T,POUCH,"Rug or soft surface",QUIET], sessions:3, minutes:5, reps:"8–10 reps per session",
 steps:["Ask for a sit. Hold a treat at {dog}’s nose and slowly lower it straight down between their front paws.","Then slowly draw it along the floor away from them, making an ‘L’ shape. Mark “Yes!” the moment their elbows touch the floor, and treat on the floor between their paws.","If their rear pops up, just restart and go slower. You can also lure under your bent knee like a tunnel.","After about 5 lured reps, use the same motion with an empty hand and reward from your other hand.","Shrink the motion to a flat palm lowered toward the floor. Then add the word “Down” just before the hand signal."],
 success:["{dog} lies down on the hand signal with an empty hand, 4 out of 5 times."],
 mistakes:["Pushing on {dog}’s shoulders or pulling legs out — never needed.","Luring too fast. Slow and steady keeps their nose glued to your hand.","Marking late, after {dog} has already popped back up.","Practicing on cold, slippery floors — many dogs won’t lie down there."],
 levelUp:"‘Puppy push-ups’: sit → down → sit → down, rewarding every 2nd or 3rd position."},
{skill:null, review:true, skills:["marker","name","focus","touch","sit","down"], title:"Review Day: Week 1 Foundations", goal:"Check in on every week-1 skill and celebrate what {dog} has learned.",
 why:"Review days consolidate learning and show you which skills are solid and which need a little more practice before you build on them.",
 need:[T,POUCH,MAT], sessions:3, minutes:5, reps:"Mix all skills in each session",
 steps:["Warm up with 5 quick Name Game reps.","Do a rapid-fire round: 3 hand touches, 3 sits, 3 downs, and one 3-second ‘Look’. Reward every success.","Repeat the round in a different room — new places are harder, so be generous with rewards.","Note which skills felt shaky (slow responses, needed a lure). Spend an extra minute on those.","End with something {dog} loves: a game of tug, a sniff walk, or a chew."],
 success:["You can name {dog}’s strongest and weakest skills, and you’ve noted them below.","{dog} responds to name, touch, sit and down in two different rooms."],
 mistakes:["Turning review into a test and getting frustrated. If something’s rusty, just make it easier.","Long sessions — keep each one under 5 minutes."],
 levelUp:"Try each cue while you’re sitting in a chair instead of standing."}
);
